
DECLARE @COMPANYID INT = 7 
DECLARE @STARTDATE DATETIME 
DECLARE @ENDDATE DATETIME 

SELECT COUNT(1) 
FROM OPCTAGRESULT WITH(NOLOCK, INDEX(IX_OPCTAGRESULT)) 
WHERE COMPANYID = @COMPANYID AND 
	INSERTDATE >= @STARTDATE AND 
	INSERTDATE <= @ENDDATE